package com.teamresourceful.fruits.common.registry;

import com.teamresourceful.fruits.common.lib.Constants;
import net.minecraft.world.food.FoodProperties;

public class ModFoods {
    private ModFoods() {
        throw new IllegalStateException(Constants.UTILITY_CLASS);
    }

    public static final FoodProperties ACAI_BERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties AGAVE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties APRICOT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties AVOCADO = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BANANA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BLACKBERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BLUEBERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CANTALOUPE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CHERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties COCONUT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CRANBERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties DATE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties DRAGON_FRUIT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties FIG = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties GRAPE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties GRAPEFRUIT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties GUAVA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties HONEYDEW = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties HUCKLEBERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties JACKFRUIT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties JOJOBA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties KIWI = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties LEMON = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties LIME = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties MANDARIN = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties MANGO = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties MESQUITE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties MULBERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties NONI = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties OLIVE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties ORANGE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PAPAYA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PASSION_FRUIT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PEACH = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PEAR = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PINEAPPLE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PINE_BERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PINE_NUT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PLUM = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties POMEGRANATE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PRICKLY_PEAR = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties RAISINS = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties SAGUARO = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties STARFRUIT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties STAR_APPLE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties STRAWBERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties WOLFBERRY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties ZUCCHINI = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties ARROWROOT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties ARUGULA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties ARTICHOKE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties ASPARAGUS = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BEANS = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BROCCOLI = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BRUSSEL_SPROUT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BELL_PEPPER = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties BOK_CHOY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CABBAGE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CAULIFLOWER = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CELERY = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CHILLI_PEPPER = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties CUCUMBER = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties EGGPLANT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties FENNEL = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties GARLIC = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties GINGER = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties KALE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties LEEK = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties LETTUCE = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties OKRA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties ONION = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PARSNIP = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties PEA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties SNOW_PEA = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties RADISH = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties RHUBARB = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties SHALLOT = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties SPINACH = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties SPRING_ONION = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties SWEETCORN = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties TOMATO = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties TURMERIC = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
    public static final FoodProperties TURNIP = new FoodProperties.Builder().nutrition(2).saturationMod(1).fast().build();
}
